# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Medonapp iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Medonapp iOS

  pod 'Alamofire'
  pod 'Kingfisher', '~> 7.0'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'SwiftValidator', :git => 'https://github.com/jpotts18/SwiftValidator.git', :tag => '4.2.0'

end
