# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Medonapp iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Medonapp iOS

  pod 'Alamofire', '>= 5.6.2'
  pod 'Kingfisher', '~> 7.0'
  pod 'SwiftValidator', :git => 'https://github.com/jpotts18/SwiftValidator.git', :tag => '4.2.0'
  pod 'DPOTPView'
  pod 'lottie-ios'
  pod 'iOSDropDown'
  pod 'SkeletonView'
  pod 'Toast-Swift', '~> 5.0.1'
  pod 'Popovers'
  pod 'FaveButton'

end
